# Generated by Django 4.2.16 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, default='TEST', max_length=255),
            preserve_default=False,
        ),
    ]
