# Generated by Django 4.2.16 on 2026-06-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
