# Generated by Django 4.2.16 on 2026-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_delete_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(),
        ),
    ]
