# Generated by Django 4.2.16 on 2024-10-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Prihod'), ('expense', 'Trošak')], default='expense', max_length=7),
        ),
    ]
