# Generated by Django 4.2.16 on 2024-10-25 21:45

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    # Get the models
    CategoryGroup = apps.get_model('transactions', 'CategoryGroup')
    Category = apps.get_model('transactions', 'Category')

    # Define the data dictionary
    data = {
        # Expenses
        'ostalo': ['ostalo'],
        'nabavka': ['hrana, piće i hemija', 'odeća i obuća', 'ostalo'],
        'helena <i class="bi bi-heart-fill" style="color: red;"></i> Emilija': ['vrtić', 'igračke', 'ostalo'],
        'kuća': ['računi', 'ulaganja', 'troškovi', 'ostalo'],
        'miloš <i class="bi bi-heart-fill" style="color: red;"></i> Marija': ['ostalo'],
        'zdravlje': ['lekari', 'apoteka', 'ostalo'],
        'auto': ['gorivo', 'održavanje', 'ostalo'],
        'kompjuteri i mobilni': ['mesečna rata', 'ostalo'],

        # Incomes
        'plata': ['miloš', 'marija', 'ostalo'],
    }

    # Iterate through the data dictionary
    for group_name, categories in data.items():
        # Create CategoryGroup instance
        category_group = CategoryGroup.objects.create(name=group_name.capitalize())

        # Create Category instances linked to the current CategoryGroup
        for category_name in categories:
            Category.objects.create(name=category_name.capitalize(), category_group=category_group)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_categorygroup_category'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
