# Generated by Django 4.2.16 on 2024-10-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='name_with_html',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
