# Generated by Django 4.2.16 on 2024-10-26 00:07

from django.db import migrations


def update_initial_data(apps, schema_editor):
    # Get the models
    CategoryGroup = apps.get_model('transactions', 'CategoryGroup')

    # Update data
    cg1 = CategoryGroup.objects.filter(name__icontains='marija').first()
    if cg1:
        cg1.name = 'Miloš i Marija'
        cg1.name_with_html = 'Miloš <i class="bi bi-heart-fill" style="color: red;"></i> Marija'
        cg1.save()
    cg2 = CategoryGroup.objects.filter(name__icontains='helena').first()
    if cg2:
        cg2.name = 'Helena i Emilija'
        cg2.name_with_html = 'Helena <i class="bi bi-heart-fill" style="color: red;"></i> Emilija'
        cg2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_categorygroup_name_with_html'),
    ]

    operations = [
        migrations.RunPython(update_initial_data),
    ]
