# Generated by Django 4.2.16 on 2024-10-29 23:06

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    # Get the models
    CategoryGroup = apps.get_model('transactions', 'CategoryGroup')
    Category = apps.get_model('transactions', 'Category')

    # Define the data dictionary
    data = {
        # Expenses
        'Helena i Emilija': ['stvari'],
        'Miloš i Marija': ['stvari']
    }

    # Iterate through the data dictionary
    for group_name, categories in data.items():
        # Get or create CategoryGroup instance
        category_group, _ = CategoryGroup.objects.get_or_create(name=group_name.capitalize())

        # Create Category instances linked to the current CategoryGroup
        for category_name in categories:
            Category.objects.create(name=category_name.capitalize(), category_group=category_group)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_user'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
