# Generated by Django 4.2.16 on 2024-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
