# Generated by Django 4.2.16 on 2024-11-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20241129_0028'),
        ('transactions', '0016_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='new_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_transactions', to='categories.category'),
            preserve_default=False,
        ),
    ]
