# Generated by Django 4.2.16 on 2025-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_agency_related',
            field=models.BooleanField(default=False),
        ),
    ]
