# Generated by Django 4.2.16 on 2026-05-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_transaction_is_agency_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_agency_related',
        ),
    ]
