# Generated by Django 4.2.16 on 2024-11-28 23:28

from django.db import migrations


def transfer_category_data(apps, schema_editor):
    # Get models
    OldCategoryGroup = apps.get_model('transactions', 'CategoryGroup')
    OldCategory = apps.get_model('transactions', 'Category')
    NewCategoryGroup = apps.get_model('categories', 'CategoryGroup')
    NewCategory = apps.get_model('categories', 'Category')

    # Transfer CategoryGroup data
    for old_group in OldCategoryGroup.objects.all():
        new_group = NewCategoryGroup.objects.create(
            name=old_group.name,
            name_with_html=old_group.name_with_html
        )

        # Transfer Category data
        for old_category in OldCategory.objects.filter(category_group_id=old_group.id):
            NewCategory.objects.create(
                name=old_category.name,
                category_group_id=new_group.id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0016_budget'),

    ]

    operations = [
        migrations.RunPython(transfer_category_data),
    ]
