# Generated by Django 4.2.16 on 2026-03-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20241129_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygroup',
            name='name_with_html',
        ),
    ]
