# Generated by Django 4.2.16 on 2026-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_categorygroup_name_with_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
