# Generated by Django 4.2.16 on 2026-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_end_date_category_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='end_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
