# Generated by Django 4.2.16 on 2026-06-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingitem',
            options={'ordering': ['order', 'exercise__primary_muscle', 'exercise__name']},
        ),
    ]
