# Generated by Django 4.2.16 on 2026-06-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_trainingitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingitem',
            options={'ordering': ['order', 'exercise__muscle_group', 'exercise__name']},
        ),
    ]
