# Generated by Django 4.2.16 on 2026-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_exercise_options_and_more'),
        ('trainings', '0003_alter_trainingitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='muscle_groups',
            field=models.ManyToManyField(related_name='trainings', to='exercises.musclegroup'),
        ),
    ]
