# Generated by Django 4.2.16 on 2026-06-27 19:43

from django.db import migrations


def forwards(apps, schema_editor):
    Training = apps.get_model("trainings", "Training")
    MuscleGroup = apps.get_model("exercises", "MuscleGroup")

    muscle_groups = {mg.name.lower(): mg for mg in MuscleGroup.objects.all()}
    for training in Training.objects.all():
        words = training.name.lower().split()
        for word in words:
            muscle = muscle_groups.get(word)
            if muscle:
                training.muscle_groups.add(muscle)


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_training_muscle_groups'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
