# Generated by Django 4.2.16 on 2026-06-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20260627_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='name',
        ),
    ]
