# Generated by Django 4.2.16 on 2026-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.CharField(choices=[('Grudi', 'Grudi'), ('Leđa', 'Leđa'), ('Ramena', 'Ramena'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Noge', 'Noge'), ('Stomak', 'Stomak'), ('Kardio', 'Kardio')], default='cardio', max_length=20),
            preserve_default=False,
        ),
    ]
