# Generated by Django 4.2.16 on 2026-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
