# Generated by Django 4.2.16 on 2026-06-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['primary_muscle', 'name']},
        ),
    ]
