# Generated by Django 4.2.16 on 2026-06-27 19:10

from django.db import migrations


def forwards(apps, schema_editor):
    MuscleGroup = apps.get_model("exercises", "MuscleGroup")
    Exercise = apps.get_model("exercises", "Exercise")

    muscle_names = [
        "Grudi",
        "Leđa",
        "Ramena",
        "Biceps",
        "Triceps",
        "Noge",
        "Stomak",
        "Kardio",
    ]

    muscle_map = {}
    for name in muscle_names:
        muscle, _ = MuscleGroup.objects.get_or_create(name=name)
        muscle_map[name] = muscle

    for exercise in Exercise.objects.all():
        exercise.muscle_group = muscle_map[exercise.primary_muscle]
        exercise.save(update_fields=["muscle_group"])


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_musclegroup_exercise_muscle_group'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
