# Generated by Django 4.2.16 on 2026-06-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20260627_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['muscle_group', 'name']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscle',
        ),
    ]
