# Generated by Django 4.2.16 on 2024-11-28 23:20

from django.db import migrations


def transfer_budget_data(apps, schema_editor):
    # Get models
    OldBudget = apps.get_model('transactions', 'Budget')
    NewBudget = apps.get_model('budgets', 'Budget')

    # Copy data from old to new table
    for old_budget in OldBudget.objects.all():
        NewBudget.objects.create(
            category=old_budget.category,
            start_date=old_budget.start_date,
            end_date=old_budget.end_date,
            amount=old_budget.amount
        )


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('transactions', '0016_budget'),
    ]

    operations = [
        migrations.RunPython(transfer_budget_data),
    ]
