# Generated by Django 4.2.16 on 2024-11-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20241129_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
