# Generated by Django 4.2.16 on 2025-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
