# Generated by Django 4.2.16 on 2026-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='quantity_grams',
            field=models.IntegerField(),
        ),
    ]
