# Generated by Django 4.2.16 on 2026-06-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_calories_alter_food_carbs_alter_food_fat_and_more'),
        ('consumptions', '0002_alter_consumption_quantity_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='foods.food'),
        ),
    ]
